version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2

    steps:
      - checkout

      - run:
          name: INSTALL DEPENDENCIES
          command: pip install -r dev-requirements.txt

      - run:
          name: RUN TESTS AND COLLECT COVERAGE
          command: pytest --cov=mhddq

      - codecov/upload

workflows:
  version: 2.1

  build-test:
    jobs:
      - build
